name: zish_python_antlr

on: [push]

jobs:
  main-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    container: python:${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytz .

      - name: Test with pytest
        run: |
          python -m pytest -x -v -W error test --ignore=test/test_readme.py

  static-test:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-alphabetize pytest black Sphinx .
      - name: Lint check
        run: |
          black --check .
          flake8 .
          python -m pytest -x -v -W error test/test_readme.py
          rst2html.py README.rst README.html
